version: '3.8'
services:
  db:
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
      POSTGRES_DB: arbitrage_demo

  alert-agent:
    profiles: ['disabled']

  scheduler:
    profiles: ['disabled']
