{{- if .Values.logForwarder.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-forwarder
spec:
  selector:
    matchLabels:
      app: log-forwarder
  template:
    metadata:
      labels:
        app: log-forwarder
    spec:
      containers:
        - name: fluent-bit
          image: {{ .Values.logForwarder.image }}
          resources: {{- toYaml .Values.logForwarder.resources | nindent 12 }}
          env:
            - name: LOKI_HOST
              value: "loki:3100"
{{- end }}
