apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
    {{- include "crypto-arbitrage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: {{ .Values.analytics.image }}
          ports:
            - containerPort: {{ .Values.analytics.port }}
          resources: {{- toYaml .Values.analytics.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: analytics-secrets
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.analytics.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.analytics.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
    - port: {{ .Values.analytics.port }}
      targetPort: {{ .Values.analytics.port }}
