apiVersion: apps/v1
kind: Deployment
metadata:
  name: executor
  labels:
    app: executor
    {{- include "crypto-arbitrage.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: executor
  template:
    metadata:
      labels:
        app: executor
    spec:
      containers:
        - name: executor
          image: {{ .Values.executor.image }}
          resources: {{- toYaml .Values.executor.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: executor-secrets
          readinessProbe:
            exec:
              command: ["pgrep", "-f", "Executor"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pgrep", "-f", "Executor"]
            initialDelaySeconds: 10
            periodSeconds: 10
