apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: default
spec:
  encryptedData:
    binanceKey: AgBINANCEKEYPLACEHOLDER
    gmailPassword: AgGMAILPASSWORDPLACEHOLDER
    telegramToken: AgTELEGRAMTOKENPLACEHOLDER
