FROM node:20-bullseye
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile && yarn build
RUN test -f index.html || cp public/index.html index.html
# Expose dashboard port
EXPOSE 3000
CMD ["yarn", "preview", "--port", "3000"]
