replicaCount: 1
secrets:
  useSealed: true  # use Bitnami SealedSecrets by default

# ---------------------------------------------------------------------
# Service-level configuration
# ---------------------------------------------------------------------

api:
  image: arb-api
  port: 8080
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  env:
    # JWT_SECRET: "change-me"
    # PGHOST: "postgres"
    # PGUSER: "arb_user"
    # PGPASSWORD: "secret"
    # PGDATABASE: "arbitrage"
    # SANDBOX_MODE: "false"

analytics:
  image: arb-analytics
  port: 5000
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
      nvidia.com/gpu: "1"
    limits:
      cpu: "1000m"
      memory: "1Gi"
      nvidia.com/gpu: "1"
  env:
    # MODEL_PATH: "/models/model.h5"
    # GPU_ENABLED: "true"
    # LOG_LEVEL: "INFO"

dashboard:
  image: arb-dashboard
  port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  env:
    # PUBLIC_URL: "https://arb.example.com"
    # NODE_ENV: "production"

executor:
  image: arb-executor
  resources:
    requests:
      cpu: "250m"
    limits:
      cpu: "500m"
  env:
    # REDIS_HOST: "redis"
    # REDIS_PORT: "6379"
    # ANALYTICS_URL: "http://analytics:5000/trade"
    # PERSONALITY_MODE: "REALISTIC"
    # STARTING_BALANCE: "10000"
