apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: arb-analytics
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /ping
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
              nvidia.com/gpu: 1
            limits:
              cpu: "1000m"
              memory: "1Gi"
              nvidia.com/gpu: "1"
          envFrom:
            - secretRef:
                name: analytics-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
    - port: 5000
      targetPort: 5000
