apiVersion: v1
kind: Secret
metadata:
  name: prod-secrets
type: Opaque
stringData:
  EXECUTION_MODE: sandbox
  REDIS_URL: redis://default:testpassword@redis:6379
  POSTGRES_URL: mocked
  EXTERNAL_API_KEY: dummy
  INTERNAL_TOKEN: test-token
