apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: default
spec:
  encryptedData:
    binanceKey: AgFAKEENCRYPTEDBINANCEKEY
    gmailPassword: AgFAKEENCRYPTEDGMAILPASS
    telegramToken: AgFAKEENCRYPTEDTELEGRAMTOKEN
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: analytics-secrets
  namespace: default
spec:
  encryptedData:
    PGHOST: AgFAKEENCRYPTEDPGHOST
    PGUSER: AgFAKEENCRYPTEDPGUSER
    PGPASSWORD: AgFAKEENCRYPTEDPGPASSWORD
    PGDATABASE: AgFAKEENCRYPTEDPGDATABASE
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dashboard-secrets
  namespace: default
spec:
  encryptedData:
    PUBLIC_URL: AgFAKEDASHBOARDURL
    NODE_ENV: AgFAKEDASHBOARDENV
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: executor-secrets
  namespace: default
spec:
  encryptedData:
    REDIS_HOST: AgFAKEREDISHOST
    REDIS_PORT: AgFAKEREDISPORT
    ANALYTICS_URL: AgFAKEANALYTICSURL
