name: CI

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare test results directory
        run: mkdir -p test-results

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman
      - name: Install kubectl and jq
        run: |
          sudo apt-get update
          sudo apt-get -y install kubectl jq


      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz \
            | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes YAML
        run: kubeconform -strict -ignore-missing-schemas -summary infra/k8s/

      - name: Run API tests
        run: |
          mkdir -p ../test-results
          npm test -- --json --outputFile=../test-results/api-jest.json
        working-directory: api

      - name: Upload API test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: api-jest-report
          path: test-results/api-jest.json

      - name: Run API ESLint
        run: npx eslint .
        working-directory: api

      - name: Build api image
        run: podman build -t api ./api

      - name: Run Trivy scan on api
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: api
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Run Dashboard tests
        run: |
          mkdir -p ../test-results
          npx jest --json --outputFile=../test-results/dashboard-jest.json
        working-directory: dashboard

      - name: Upload Dashboard test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: dashboard-jest-report
          path: test-results/dashboard-jest.json

      - name: Run Dashboard ESLint
        run: npx eslint .
        working-directory: dashboard

      - name: Build dashboard image
        run: podman build -t dashboard ./dashboard

      - name: Run Trivy scan on dashboard
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dashboard
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Install feed-aggregator dependencies
        run: npm install
        working-directory: feed-aggregator

      - name: Run feed-aggregator tests
        run: |
          mkdir -p ../test-results
          pytest --junitxml=../test-results/feed-aggregator-pytest.xml
        working-directory: feed-aggregator

      - name: Upload feed-aggregator test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: feed-aggregator-pytest-report
          path: test-results/feed-aggregator-pytest.xml

      - name: Build feed-aggregator image
        run: podman build -t feed-aggregator ./feed-aggregator

      - name: Run Trivy scan on feed-aggregator
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: feed-aggregator
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Install Python dependencies for analytics
        run: pip install -r requirements.txt

      - name: Run Analytics tests
        run: |
          mkdir -p ../test-results
          pytest --junitxml=../test-results/analytics-pytest.xml
        working-directory: analytics
        
      - name: Upload analytics test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: analytics-pytest-report
          path: test-results/analytics-pytest.xml
          
      - name: Run flake8
        run: flake8 analytics/
        
      - name: Build analytics image
        run: podman build -t analytics ./analytics

      - name: Run Trivy scan on analytics
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: analytics
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Run Executor tests
        run: |
          mkdir -p ../test-results/maven
          mvn test
          cp -r target/surefire-reports ../test-results/maven || true
        working-directory: executor

      - name: Upload Executor test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: executor-maven-report
          path: test-results/maven
        
      - name: Run Maven Checkstyle
        run: mvn checkstyle:check
        working-directory: executor
        
      - name: Build executor image
        run: podman build -t executor ./executor

      - name: Run Trivy scan on executor
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: executor
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

  behavior-tests:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install kubectl and jq
        run: |
          sudo apt-get update
          sudo apt-get -y install kubectl jq
      - name: Run behavior simulation tests
        run: bash scripts/test-behavior.sh

