name: CI

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
    with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Validate Kubernetes YAML
        run: kubectl apply --dry-run=client -f infra/k8s/

      - name: Run API tests
        run: npm test
        working-directory: api

      - name: Run API ESLint
        run: npx eslint .
        working-directory: api

      - name: Build api image
        run: podman build -t api ./api

      - name: Run Trivy scan on api
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: api
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Run Dashboard tests
        run: npx jest
        working-directory: dashboard

      - name: Run Dashboard ESLint
        run: npx eslint .
        working-directory: dashboard

      - name: Build dashboard image
        run: podman build -t dashboard ./dashboard

      - name: Run Trivy scan on dashboard
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dashboard
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Run Analytics tests
        run: pytest
        working-directory: analytics
        
      - name: Run flake8
        run: flake8 analytics/
        
      - name: Build analytics image
        run: podman build -t analytics ./analytics

      - name: Run Trivy scan on analytics
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: analytics
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Run Executor tests
        run: mvn test
        working-directory: executor
        
      - name: Run Maven Checkstyle
        run: mvn checkstyle:check
        working-directory: executor
        
      - name: Build executor image
        run: podman build -t executor ./executor

      - name: Run Trivy scan on executor
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: executor
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

