name: Release
on:
  release:
    types: [created]

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build service images
        run: |
          podman build -t dashboard ./dashboard
          podman build -t api ./api
          podman build -t executor ./executor
          podman build -t analytics ./analytics
          podman build -t feed-aggregator ./feed-aggregator

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/v1.28.0/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Generate SBOMs
        run: |
          set -e
          syft dashboard:latest -o json > sbom-dashboard.json
          syft api:latest -o json > sbom-api.json
          syft executor:latest -o json > sbom-executor.json
          syft analytics:latest -o json > sbom-analytics.json
          syft feed-aggregator:latest -o json > sbom-feed-aggregator.json

      - name: Upload SBOMs and CHANGELOG to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sbom-*.json
            CHANGELOG.md
