name: Release
on:
  release:
    types: [created]

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        # actions/checkout@v3 SHA f43a0e5ff2bd294095638e18286ca9a3d1956744
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Setup Node.js
        # actions/setup-node@v3 SHA 3235b876344d2a9aa001b8d1453c930bba69e610
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: 18

      - name: Setup Python
        # actions/setup-python@v4 SHA 7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
        with:
          python-version: '3.10'

      - name: Setup Java
        # actions/setup-java@v3 SHA 17f84c3641ba7b8f6deff6309fc4c864478f5d62
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Build service images
        run: |
          podman build -t dashboard ./dashboard
          podman build -t api ./api
          podman build -t executor ./executor
          podman build -t analytics ./analytics
          podman build -t feed-aggregator ./feed-aggregator

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/v1.28.0/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Generate SBOMs
        run: |
          set -e
          syft dashboard:latest -o json > sbom-dashboard.json
          syft api:latest -o json > sbom-api.json
          syft executor:latest -o json > sbom-executor.json
          syft analytics:latest -o json > sbom-analytics.json
          syft feed-aggregator:latest -o json > sbom-feed-aggregator.json

      - name: Upload SBOMs and CHANGELOG to GitHub Release
        # softprops/action-gh-release@v1 SHA 26994186c0ac3ef5cae75ac16aa32e8153525f77
        uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77
        with:
          files: |
            sbom-*.json
            CHANGELOG.md
